services:
  db:
    container_name: postgresql-18
    build: 
      context: .
      dockerfile: Dockerfile
    shm_size: 2g
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # POSTGRES_DB: postgres
    command: |
      postgres
      -c 'max_connections=100'
      -c 'default_toast_compression=lz4'
      -c 'shared_preload_libraries=timescaledb'
      -c 'effective_cache_size=4GB'
      -c 'shared_buffers=2GB'
      -c 'work_mem=50MB'
      -c 'maintenance_work_mem=256MB'
      -c 'effective_io_concurrency=200'
      -c 'random_page_cost=1.1'
      -c 'cpu_tuple_cost=0.03'
      -c 'max_worker_processes=16'
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - data:/var/lib/postgresql/data
      
volumes:
  data:
  
networks:
  default:
    external: true
    name: base
